apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: NGI-demo
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1a: { id: subnet-0e78bedd6dc053b07 }
      us-east-1b: { id: subnet-06318b3ebd227e9fd }
      us-east-1c: { id: subnet-0616914ee2c3034d5 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
